# Generated by Django 3.1.7 on 2021-04-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
