# Generated by Django 3.1.7 on 2021-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210425_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
