# Generated by Django 3.2.3 on 2021-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210425_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='prazo',
            field=models.CharField(default='Sem Prazo', max_length=12),
        ),
    ]
