# Generated by Django 3.2.3 on 2021-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='prazo',
            field=models.CharField(default='Sem Prazo', max_length=15),
        ),
    ]
