# Generated by Django 3.1.7 on 2021-05-31 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0008_auto_20210525_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='users',
            field=models.ManyToManyField(related_name='dono', to=settings.AUTH_USER_MODEL),
        ),
    ]
